# Generated by Django 5.2.6 on 2025-12-20 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_holiday", models.DateField(unique=True)),
                ("name_of_holiday", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                ("due_date", models.DateField(null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pending_with_chief_manager", "To be approved"),
                            ("review", "In review"),
                            ("revision", "Revised document to be uploaded"),
                            ("submitted", "Submitted"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cfac", "CFAC"),
                            ("compliance", "Compliance"),
                            ("health", "Health"),
                            ("motor_tp", "Motor TP"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "uiic_contact",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "compliance_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "circular_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_of_compliance",
                    models.CharField(
                        choices=[
                            ("adhoc", "Adhoc"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("halfyearly", "Halfyearly"),
                            ("annual", "Annual"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "return_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "circular_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "inbound_email_communication",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "outbound_email_communication",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "data_document_template",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "data_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[(3, "High"), (2, "Medium"), (1, "Low")],
                        default=2,
                        null=True,
                    ),
                ),
                (
                    "date_of_document_received",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "date_of_document_forwarded",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="compliance.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                (
                    "due_date_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of days must be at least 1",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "type_of_due_date",
                    models.CharField(
                        choices=[("calendar", "Calendar"), ("working", "Working")],
                        default="calendar",
                        max_length=100,
                    ),
                ),
                (
                    "recurring_task_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cfac", "CFAC"),
                            ("compliance", "Compliance"),
                            ("health", "Health"),
                            ("motor_tp", "Motor TP"),
                        ]
                    ),
                ),
                ("uiic_contact", models.CharField(max_length=1000)),
                ("compliance_contact", models.CharField(max_length=100)),
                (
                    "circular_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_of_compliance",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("halfyearly", "Halfyearly"),
                            ("annual", "Annual"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "recurring_interval",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("halfyearly", "Halfyearly"),
                            ("annual", "Annual"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "return_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "circular_document",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "data_document_template",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[(3, "High"), (2, "Medium"), (1, "Low")],
                        default=2,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repeat_month",
                    models.ManyToManyField(blank=True, to="compliance.month"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template",
                to="compliance.template",
            ),
        ),
    ]
