# Generated by Django 5.1.6 on 2025-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancetopic",
            name="recurring_task_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
