# Generated by Django 5.2.6 on 2025-12-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_department_alter_customuser_options_and_more"),
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.department"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.department"
            ),
        ),
    ]
