# Generated by Django 6.0 on 2025-12-18 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='due_date_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days must be at least 1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
