# Generated by Django 5.1.6 on 2025-02-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_compliancetopic_recurring_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('due_date_days', models.IntegerField(default=0)),
                ('type_of_due_date', models.CharField(blank=True, choices=[('calendar_days', 'Calendar days'), ('working_days', 'Working days')], default='', max_length=100)),
                ('recurring_task_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('uiic_contact', models.CharField(max_length=1000)),
                ('compliance_contact', models.CharField(max_length=100)),
                ('circular_details', models.CharField(blank=True, max_length=100)),
                ('type_of_compliance', models.CharField(blank=True, choices=[('adhoc', 'Ad-hoc'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-yearly'), ('annual', 'Annual')], max_length=100)),
                ('recurring_interval', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-yearly'), ('annual', 'Annual')], max_length=100)),
                ('repeat_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100)),
                ('return_number', models.CharField(blank=True, max_length=100)),
                ('circular_document', models.FileField(blank=True, upload_to='')),
                ('priority', models.IntegerField(blank=True, choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=2)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ComplianceTopic',
            new_name='Task',
        ),
        migrations.DeleteModel(
            name='RecurringTask',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='statement_name',
            new_name='task_name',
        ),
    ]
