# Generated by Django 6.0 on 2025-12-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("compliance", "0003_task_circular_url_template_circular_url"),
        ("compliance", "0004_alter_task_circular_document_and_more"),
    ]

    dependencies = [
        ("compliance", "0002_alter_task_department_alter_template_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="circular_url",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Source circular URL",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="circular_url",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Source circular URL",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="circular_document",
            field=models.FileField(
                blank=True, null=True, upload_to="circulars_document/"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="data_document",
            field=models.FileField(blank=True, null=True, upload_to="data_document/"),
        ),
        migrations.AlterField(
            model_name="task",
            name="data_document_template",
            field=models.FileField(
                blank=True, null=True, upload_to="data_document_template/"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="inbound_email_communication",
            field=models.FileField(blank=True, null=True, upload_to="inbound_email/"),
        ),
        migrations.AlterField(
            model_name="task",
            name="outbound_email_communication",
            field=models.FileField(blank=True, null=True, upload_to="outbound_email/"),
        ),
        migrations.AlterField(
            model_name="template",
            name="circular_document",
            field=models.FileField(
                blank=True, null=True, upload_to="circulars_document/"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="data_document_template",
            field=models.FileField(
                blank=True, null=True, upload_to="data_document_template/"
            ),
        ),
    ]
