# Generated by Django 5.1.6 on 2025-02-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0003_template_rename_compliancetopic_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="repeat_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=100,
            ),
        ),
    ]
