# Generated by Django 6.0.1 on 2026-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "compliance",
            "0003_task_circular_url_template_circular_url_and_alter_task_circular_document_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date", "priority"]},
        ),
        migrations.AddField(
            model_name="task",
            name="board_meeting_date",
            field=models.DateField(
                blank=True,
                help_text="Date on which the board adopted the item",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_of_document_forwarded",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date of submission to IRDA",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_of_document_received",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date of document received",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_due_date",
            field=models.CharField(
                choices=[
                    ("calendar", "Calendar"),
                    ("working", "Working"),
                    ("board_meeting", "Board meeting"),
                ],
                default="calendar",
                max_length=100,
            ),
        ),
    ]
