# Generated by Django 6.0.1 on 2026-01-26 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0004_alter_task_options_task_board_meeting_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="board_meeting_date_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="template",
            name="alternate_due_date_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="To be entered if due date type is board meeting conditional (e.g. 180 days)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="conditional_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("earlier", "Whichever is earlier"),
                    ("later", "Whichever is later"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="board_meeting_date",
            field=models.DateField(
                blank=True, help_text="Date of board meeting if applicable", null=True
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_due_date",
            field=models.CharField(
                choices=[
                    ("calendar", "Calendar"),
                    ("working", "Working"),
                    ("board_meeting", "Board meeting"),
                    ("board_meeting_conditional", "Board meeting (conditional)"),
                ],
                default="calendar",
                max_length=100,
            ),
        ),
    ]
