# Generated by Django 5.1.6 on 2025-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0004_task_repeat_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="recurring_task_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type_of_compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Adhoc", "Adhoc"),
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Fortnightly", "Fortnightly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Halfyearly", "Halfyearly"),
                    ("Annual", "Annual"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="recurring_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Fortnightly", "Fortnightly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Halfyearly", "Halfyearly"),
                    ("Annual", "Annual"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="recurring_task_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Adhoc", "Adhoc"),
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Fortnightly", "Fortnightly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Halfyearly", "Halfyearly"),
                    ("Annual", "Annual"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_due_date",
            field=models.CharField(
                blank=True,
                choices=[("Calendar", "Calendar"), ("Working", "Working")],
                default="",
                max_length=100,
            ),
        ),
    ]
