# Generated by Django 5.2.6 on 2025-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0005_alter_task_recurring_task_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="current_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("submitted", "Submitted")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type_of_compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adhoc", "Adhoc"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("halfyearly", "Halfyearly"),
                    ("annual", "Annual"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="recurring_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("halfyearly", "Halfyearly"),
                    ("annual", "Annual"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adhoc", "Adhoc"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("halfyearly", "Halfyearly"),
                    ("annual", "Annual"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_due_date",
            field=models.CharField(
                blank=True,
                choices=[("calendar", "Calendar"), ("working", "Working")],
                default="calendar",
                max_length=100,
            ),
        ),
    ]
