# Generated by Django 6.0.1 on 2026-01-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0005_task_board_meeting_date_flag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicholiday",
            options={"ordering": ["date_of_holiday"]},
        ),
        migrations.AddField(
            model_name="task",
            name="outbound_data_document",
            field=models.FileField(
                blank=True, null=True, upload_to="outbound_data_document/"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="data_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="data_document/",
                verbose_name="Inbound data document",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type_of_compliance",
            field=models.CharField(
                choices=[
                    ("adhoc", "Adhoc"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("halfyearly", "Halfyearly"),
                    ("annual", "Annual"),
                    ("public_disclosure", "Public disclosure"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type_of_compliance",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("halfyearly", "Halfyearly"),
                    ("annual", "Annual"),
                    ("public_disclosure", "Public disclosure"),
                ],
                max_length=100,
            ),
        ),
    ]
