# Generated by Django 6.0.1 on 2026-02-09 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0006_alter_publicholiday_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REGULATIONS", "Regulations"),
                            ("CIRCULAR", "Circular"),
                            ("NOTIFICATION", "Notification"),
                            ("GUIDELINES", "Guidelines"),
                            ("ORDER", "Order"),
                            ("NOTICE", "Notice"),
                            ("EXPOSURE_DRAFT", "Exposure Draft"),
                            ("OTHER_COMMUNICATION", "Other communication"),
                        ]
                    ),
                ),
                ("title", models.CharField()),
                (
                    "url_of_publication",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL of publication"
                    ),
                ),
                (
                    "publication_document",
                    models.FileField(
                        blank=True, null=True, upload_to="regulatory_publication"
                    ),
                ),
                (
                    "date_of_publication",
                    models.DateField(
                        verbose_name="Date of publication in IRDAI website"
                    ),
                ),
                ("effective_from", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
