# Generated by Django 6.0.1 on 2026-02-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0007_regulatorypublication"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reason_for_delay",
            field=models.TextField(
                blank=True,
                help_text="Mandatory if task is submitted after due date",
                null=True,
            ),
        ),
    ]
