# Generated by Django 6.0.2 on 2026-02-15 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0008_task_reason_for_delay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_date", "priority"],
                "permissions": [
                    ("can_mark_as_pending", "Can mark task as approved or pending"),
                    ("can_edit_as_department", "Can edit task as department user"),
                    ("can_edit_as_compliance", "Can edit task as compliance user"),
                    ("can_view_as_compliance", "Can view task as compliance user"),
                ],
            },
        ),
    ]
