from django.urls import path
from django.views.generic import RedirectView
from . import views


urlpatterns = [
    path(
        "templates/",
        views.TemplateListView.as_view(),
        name="template_list",
    ),
    path(
        "templates/add",
        views.TemplateCreateView.as_view(),
        name="template_add",
    ),
    path(
        "templates/<int:pk>/",
        views.TemplateDetailView.as_view(),
        name="template_detail",
    ),
    path(
        "templates/<int:pk>/edit/",
        views.TemplateUpdateView.as_view(),
        name="template_edit",
    ),
    path(
        "tasks/add/",
        views.TaskCreateView.as_view(),
        name="task_add",
    ),
    path(
        "tasks/<int:pk>/edit/",
        views.TaskUpdateView.as_view(),
        name="task_edit",
    ),
    path(
        "tasks/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task_detail",
    ),
    path(
        "tasks/approval/pending/",
        views.TaskApprovalPendingListView.as_view(),
        name="task_list_approval_pending",
    ),
    # 3. Status AND Recurrence Filter (e.g., tasks/overdue/monthly)
    path(
        "tasks/approval/pending/<str:recurrence>/",
        views.TaskApprovalPendingListView.as_view(),
        name="task_list_filtered_recurrence_approval_pending",
    ),
    path(
        "tasks/review/pending/",
        views.TaskReviewListView.as_view(),
        name="task_list_review",
    ),
    # 3. Status AND Recurrence Filter (e.g., tasks/overdue/monthly)
    path(
        "tasks/review/pending/<str:recurrence>/",
        views.TaskReviewListView.as_view(),
        name="task_list_filtered_recurrence_review",
    ),
    path(
        "tasks/revision/pending/",
        views.TaskRevisionListView.as_view(),
        name="task_list_revision",
    ),
    # 3. Status AND Recurrence Filter (e.g., tasks/overdue/monthly)
    path(
        "tasks/revision/pending/<str:recurrence>/",
        views.TaskRevisionListView.as_view(),
        name="task_list_filtered_recurrence_revision",
    ),
    path(
        "tasks/submitted/",
        views.TaskSubmittedListView.as_view(),
        name="task_list_submitted",
    ),
    # 3. Status AND Recurrence Filter (e.g., tasks/overdue/monthly)
    path(
        "tasks/submitted/<str:recurrence>/",
        views.TaskSubmittedListView.as_view(),
        name="task_list_filtered_recurrence_submitted",
    ),
    path(
        "tasks/board-meeting/pending/",
        views.TaskBoardMeetingPendingListView.as_view(),
        name="task_list_board_meeting_pending",
    ),
    path(
        "tasks/board-meeting/pending/<str:recurrence>",
        views.TaskBoardMeetingPendingListView.as_view(),
        name="task_list_board_meeting_pending_recurrence",
    ),
    path(
        "tasks/board-meeting/bulk/",
        views.bulk_set_board_meeting_date,
        name="task_board_meeting_bulk",
    ),
    path(
        "tasks/<str:filter>/",
        views.TaskListView.as_view(),
        name="task_list",
    ),
    # 3. Status AND Recurrence Filter (e.g., tasks/overdue/monthly)
    path(
        "tasks/<str:filter>/<str:recurrence>/",
        views.TaskListView.as_view(),
        name="task_list_filtered_recurrence",
    ),
    path(
        "holidays_upload/",
        views.upload_public_holidays,
        name="upload_public_holidays",
    ),
    path(
        "templates/<int:pk>/",
        views.TemplateDetailView.as_view(),
        name="template_detail",
    ),
    path(
        "templates/<int:pk>/create-task/",
        views.TaskCreateFromTemplateView.as_view(),
        name="task_create_from_template",
    ),
    path(
        "templates/<int:pk>/duplicate/",
        views.TemplateDuplicateView.as_view(),
        name="template_duplicate",
    ),
    path(
        "public_holiday",
        views.PublicHolidayList.as_view(),
        name="public_holiday_list",
    ),
    path(
        "tasks/<int:pk>/revise",
        views.task_mark_revision,
        name="task_revise",
    ),
    path(
        "tasks/<int:pk>/pending",
        views.task_mark_pending,
        name="task_pending",
    ),
    path(
        "tasks/<int:pk>/approve",
        views.task_mark_approve,
        name="task_approve",
    ),
    path(
        "tasks/<int:pk>/remarks",
        views.task_add_remarks,
        name="task_remarks",
    ),
    path(
        "publication/add",
        views.PublicationCreateView.as_view(),
        name="publication_create",
    ),
    path(
        "publication/<int:pk>",
        views.PublicationDetailView.as_view(),
        name="publication_detail",
    ),
    path(
        "publication/<int:pk>/edit",
        views.PublicationUpdateView.as_view(),
        name="publication_update",
    ),
    path("publication/", views.PublicationListView.as_view(), name="publication_list"),
    path(
        "tasks/<int:pk>/remind",
        views.task_send_reminder_email,
        name="task_remind",
    ),
]

urlpatterns += [path("", RedirectView.as_view(url="tasks/due-today/", permanent=True))]
