# Generated by Django 5.2.6 on 2025-12-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("staff", "Compliance Staff"),
                            ("admin", "Compliance Admin"),
                            ("viewer", "Compliance Viewer"),
                            ("dept_user", "Department User"),
                            ("dept_chief_manager", "Department Chief Manager"),
                            ("dept_dgm", "Department DGM"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cfac", "CFAC"),
                            ("compliance", "Compliance"),
                            ("health", "Health"),
                            ("motor_tp", "Motor TP"),
                        ],
                        max_length=100,
                    ),
                ),
                ("reset_password", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
