# Generated by Django 5.2.6 on 2025-12-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(unique=True)),
            ],
            options={
                "ordering": ["department_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["department", "user_type", "username"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.department",
            ),
        ),
    ]
