# Generated by Django 6.0 on 2025-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_department_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("dept_user", "Department User"),
                    ("dept_agm", "Department AGM"),
                    ("dept_dgm", "Department DGM"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
