# Generated by Django 6.0.1 on 2026-01-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("dept_user", "Department User"),
                    ("dept_agm", "Department Chief Manager"),
                    ("dept_dgm", "Department DGM"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
