# Generated by Django 6.0.1 on 2026-02-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
