# Generated by Django 6.0.1 on 2026-02-16 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_email_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["department", "username"]},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
    ]
